changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: "Features"
      labels:
        - enhancement
    - title: "Documentation"
      labels:
        - documentation
    - title: "Maintenance & dependencies"
      labels:
        - maintenance
        - dependencies
