ci:
  skip: [mypy-code]

repos:

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "--skip", "poetry.lock"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [tomli]
    files: "^(src/)"

- repo: local
  hooks:
  - id: mypy-code
    name: "mypy: checks on code"
    entry: "python -m mypy"
    language: system
    types: [python]
    require_serial: true
    files: "^(src/)"

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2023
      files: '(src|tests)/.*\.(py)'
