repos:

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [tomli]
    files: "^(src/)"

- repo: local
  hooks:
  - id: mypy-code
    name: "mypy: checks on code"
    entry: mypy
    language: python
    types: [python]
    require_serial: true
    args: ["--strict", "--explicit-package-bases"]
    files: "^(src/)"
    additional_dependencies: ["mypy==1.0.1"]