"""
Models
"""
from datetime import datetime

from ansys.grantami.serverapi_openapi import models


class RecordListHeader:
    """
    Describes a RecordList as obtained from the API
    """

    # TODO: this is a read-only model? Users would not need to create or modify it. Perhaps modify?
    def __init__(
        self,
        identifier: str,
        # metadata: Optional[Dict[str, Dict[str, object]]]=None,
        # parent_record_list_identifier: Optional[str]=None,
        created_timestamp: datetime,
        # created_user: models.GrantaServerApiListsDtoUserOrGroup=None,
        # last_modified_timestamp=None,
        # last_modified_user=None,
        # published_timestamp=None,
        # published_user=None,
        # is_revision=None,
        name: str,
        # description=None,
        # notes=None,
        published: bool,
        awaiting_approval: bool,
        # internal_use=None
    ):
        self._identifier: str = identifier
        self._created_timestamp = created_timestamp
        self._name = name
        self._published = published
        self._awaiting_approval = awaiting_approval

    @property
    def identifier(self) -> str:
        """
        Identifier of the Record List
        """
        return self._identifier

    @property
    def created_timestamp(self) -> datetime:
        """
        Datetime at which the Record List was created
        """
        return self._created_timestamp

    @property
    def name(self) -> str:
        """
        Name of the Record List
        """
        return self._name

    @property
    def published(self) -> bool:
        """
        Whether the Record List has been published or not.
        """
        return self._published

    @property
    def awaiting_approval(self) -> bool:
        """
        Whether the Record List is currently pending approval to be published or to be withdrawn.
        """
        return self._awaiting_approval

    @classmethod
    def from_model(cls, model: models.GrantaServerApiListsDtoRecordListHeader):
        """
        Instantiate from a model defined in the auto-generated client code.
        """
        return cls(
            model.identifier,
            model.created_timestamp,  # TODO typing issue in autogenerated code?
            model.name,
            model.published,
            model.awaiting_approval,
        )


class RecordListItem:
    # TODO add record guid and version, validate input (require one guid)

    def __init__(
        self,
        database_guid: str,
        table_guid: str,
        record_history_guid: str,
    ):
        self._database_guid: str = database_guid
        self._table_guid: str = table_guid
        self._record_history_guid: str = record_history_guid
        # self._record_guid = None
        # self._record_version = None

    @property
    def database_guid(self) -> str:
        return self._database_guid

    @database_guid.setter
    def database_guid(self, value: str):
        self._database_guid = value

    @property
    def table_guid(self) -> str:
        return self._table_guid

    @table_guid.setter
    def table_guid(self, value: str):
        self._table_guid = value

    @property
    def record_history_guid(self) -> str:
        return self._record_history_guid

    @record_history_guid.setter
    def record_history_guid(self, value: str):
        self._record_history_guid = value

    @classmethod
    def from_model(cls, model: models.GrantaServerApiListsDtoListItem):
        return cls(
            database_guid=model.database_guid,
            table_guid=model.table_guid,
            record_history_guid=model.record_history_guid,
        )

    def to_model(self) -> models.GrantaServerApiListsDtoListItem:
        """
        Instantiate from a model defined in the auto-generated client code.
        """
        return models.GrantaServerApiListsDtoListItem(
            database_guid=self.database_guid,
            table_guid=self.table_guid,
            record_history_guid=self.record_history_guid,
        )
