on:
  workflow_call:
    secrets:
      AZURE_APP_ID:
        required: true
      AZURE_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_RESOURCE_GROUP:
        required: true
      AZURE_VM_NAME:
        required: true
      TEST_SERVER_URL:
        required: true
      TEST_SERVER_ADMIN_USER:
        required: true
      TEST_SERVER_ADMIN_PASS:
        required: true
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:

concurrency:
  group: integration-server
  cancel-in-progress: false

jobs:
  start_vm:
    name: Start Azure VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start VM with Azure CLI
        id: azure_cli
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az vm start -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_VM_NAME }}

      - name: Check server is ready
        run: |
          pip install requests --disable-pip-version-check
          python cicd/check_server.py
        env:
          TEST_SL_URL: ${{secrets.TEST_SERVER_URL}}
          TEST_USER: ${{secrets.TEST_SERVER_ADMIN_USER}}
          TEST_PASS: ${{secrets.TEST_SERVER_ADMIN_PASS}}

  integration_tests:
    name: Integration tests
    runs-on: ${{ matrix.os }}
    needs: start_vm

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install kerberos headers (ubuntu only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libkrb5-dev

      - name: Install dependencies
        run: pip install poetry 'tox<4' --disable-pip-version-check

      - name: Download dependencies
        run: gh run download -R pyansys/grantami-serverapi-openapi -n "ansys-grantami-serverapi-openapi-wheel" -D deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with tox (integration tests only)
        run: tox -- -m "integration"
        env:
          TEST_SL_URL: ${{secrets.TEST_SERVER_URL}}
          TEST_LIST_ADMIN_USER: ${{secrets.TEST_SERVER_ADMIN_USER}}
          TEST_LIST_ADMIN_PASS: ${{secrets.TEST_SERVER_ADMIN_PASS}}

  stop_vm:
    name: Stop Azure VM
    runs-on: ubuntu-latest
    needs: integration_tests
    if: always()

    steps:
      - name: Stop Azure VM
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az vm deallocate -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_VM_NAME }} --no-wait
